version: '3'

services:
    web:
      working_dir: /project
      image: nginx
      container_name: lat_nginx
      volumes:
        - .:/project
        - ./docker/conf/nginx/conf.d/:/etc/nginx/conf.d/:ro
        - ./docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
        - "80:80"
        - "443:443"
      restart: always
      depends_on:
        - php

    php:
      working_dir: /project
      build: docker/app
      restart: always
      container_name: lat_php
      expose:
        - "9000"
      volumes:
        - .:/project
        - ./docker/conf/php:/usr/local/etc:ro

    db:
      image: mysql:5.7
      container_name: lat_mysql
      environment:
        MYSQL_ROOT_PASSWORD: lat123!@#
        MYSQL_DATABASE: lat_cms
        MYSQL_USER: mylat
        MYSQL_PASSWORD: lat123!@#
      ports:
        - 3306:3306
      volumes:
        - ./docker/dbdata:/var/lib/mysql

    adminer:
      image: clue/adminer
      container_name: adminer
      restart: always
      ports:
      - "8060:80"